### ISSUE TITLE
Speakers Too Quiet

### ISSUE THREAD

**Issue by xdMatthewbx** [Simon1511/ProjectRise-universal7880#2]
Media Volume, Ringtone, & Speakerphone are all extremely quiet even at maximum. Could the maximum volume be increased?

**Comment by Simon1511** [comment]
Increasing media volume in general is not a kernel thing, this can be done in the device-common sources for our device at github.com/LineageOS/android_device_samsung_universal7880-common

For me, all volumes have a good loudness. If you are using crDroid, you can change it in the settings. For LineageOS and pixelexperience, increasing the volume has to be done by their maintainers.
